import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import styles from './layout.module.css'
import LeftSideBar from "./component/leftSideBars/LeftSideBar";
import RightSideBar from "./component/rightSideBar/RightSideBar";
import Header from "./component/header/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className={styles.conteiner}>
          <div className={styles.leftSideBar}><LeftSideBar /></div>
          <div className={styles.main}>
            <div className={styles.header}><Header/></div>
            <div className={styles.mainContent}>{children}</div>
          </div>
          <div className={styles.rightSideBar}><RightSideBar /></div>
        </div>
      </body>
    </html>
  );
}
